In [1]:
import numpy as np, pandas as pd, statsmodels.api as sm

In [2]:
data = {'year': [2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016],
        'month': [12,11,10,9,8,7,6,5,4,3,2,1,12,11,10,9,8,7,6,5,4,3,2,1],
        'interest_rate': [2.75,2.5,2.5,2.5,2.5,2.5,2.5,2.25,2.25,2.25,2,2,2,1.75,1.75,1.75,1.75,1.75,1.75,1.75,1.75,1.75,1.75,1.75],
        'unemployment_rate': [5.3,5.3,5.3,5.3,5.4,5.6,5.5,5.5,5.5,5.6,5.7,5.9,6,5.9,5.8,6.1,6.2,6.1,6.1,6.1,5.9,6.2,6.2,6.1],
        'index_price': [1464,1394,1357,1293,1256,1254,1234,1195,1159,1167,1130,1075,1047,965,943,958,971,949,884,866,876,822,704,719]        
        }

df = pd.DataFrame(data)
print(df)

    year  month  interest_rate  unemployment_rate  index_price
0   2017     12           2.75                5.3         1464
1   2017     11           2.50                5.3         1394
2   2017     10           2.50                5.3         1357
3   2017      9           2.50                5.3         1293
4   2017      8           2.50                5.4         1256
5   2017      7           2.50                5.6         1254
6   2017      6           2.50                5.5         1234
7   2017      5           2.25                5.5         1195
8   2017      4           2.25                5.5         1159
9   2017      3           2.25                5.6         1167
10  2017      2           2.00                5.7         1130
11  2017      1           2.00                5.9         1075
12  2016     12           2.00                6.0         1047
13  2016     11           1.75                5.9          965
14  2016     10           1.75                5.8          943
15  2016      9           1.75                6.1          958
16  2016      8           1.75                6.2          971
17  2016      7           1.75                6.1          949
18  2016      6           1.75                6.1          884
19  2016      5           1.75                6.1          866
20  2016      4           1.75                5.9          876
21  2016      3           1.75                6.2          822
22  2016      2           1.75                6.2          704
23  2016      1           1.75                6.1          719

In [3]:
x = df[['interest_rate','unemployment_rate']]
y = df['index_price']
x, y

(    interest_rate  unemployment_rate
 0            2.75                5.3
 1            2.50                5.3
 2            2.50                5.3
 3            2.50                5.3
 4            2.50                5.4
 5            2.50                5.6
 6            2.50                5.5
 7            2.25                5.5
 8            2.25                5.5
 9            2.25                5.6
 10           2.00                5.7
 11           2.00                5.9
 12           2.00                6.0
 13           1.75                5.9
 14           1.75                5.8
 15           1.75                6.1
 16           1.75                6.2
 17           1.75                6.1
 18           1.75                6.1
 19           1.75                6.1
 20           1.75                5.9
 21           1.75                6.2
 22           1.75                6.2
 23           1.75                6.1,
 0     1464
 1     1394
 2     1357
 3     1293
 4     1256
 5     1254
 6     1234
 7     1195
 8     1159
 9     1167
 10    1130
 11    1075
 12    1047
 13     965
 14     943
 15     958
 16     971
 17     949
 18     884
 19     866
 20     876
 21     822
 22     704
 23     719
 Name: index_price, dtype: int64)

In [5]:
x = sm.add_constant(x)
x

    const  interest_rate  unemployment_rate
0     1.0           2.75                5.3
1     1.0           2.50                5.3
2     1.0           2.50                5.3
3     1.0           2.50                5.3
4     1.0           2.50                5.4
5     1.0           2.50                5.6
6     1.0           2.50                5.5
7     1.0           2.25                5.5
8     1.0           2.25                5.5
9     1.0           2.25                5.6
10    1.0           2.00                5.7
11    1.0           2.00                5.9
12    1.0           2.00                6.0
13    1.0           1.75                5.9
14    1.0           1.75                5.8
15    1.0           1.75                6.1
16    1.0           1.75                6.2
17    1.0           1.75                6.1
18    1.0           1.75                6.1
19    1.0           1.75                6.1
20    1.0           1.75                5.9
21    1.0           1.75                6.2
22    1.0           1.75                6.2
23    1.0           1.75                6.1

In [7]:
model = sm.OLS(y, x).fit()
predictions = model.predict(x)
printed_model = model.summary()
predictions, printed_model

(0     1422.862389
 1     1336.477367
 2     1336.477367
 3     1336.477367
 4     1311.462710
 5     1261.433395
 6     1286.448053
 7     1200.063031
 8     1200.063031
 9     1175.048374
 10    1063.648695
 11    1013.619381
 12     988.604723
 13     927.234359
 14     952.249016
 15     877.205045
 16     852.190387
 17     877.205045
 18     877.205045
 19     877.205045
 20     927.234359
 21     852.190387
 22     852.190387
 23     877.205045
 dtype: float64,
 <class 'statsmodels.iolib.summary.Summary'>
 """
                             OLS Regression Results
 ==============================================================================
 Dep. Variable:            index_price   R-squared:                       0.898
 Model:                            OLS   Adj. R-squared:                  0.888
 Method:                 Least Squares   F-statistic:                     92.07
 Date:                Sun, 04 Feb 2024   Prob (F-statistic):           4.04e-11
 Time:                        16:06:26   Log-Likelihood:                -134.61
 No. Observations:                  24   AIC:                             275.2
 Df Residuals:                      21   BIC:                             278.8
 Df Model:                           2
 Covariance Type:            nonrobust
 =====================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
 -------------------------------------------------------------------------------------
 const              1798.4040    899.248      2.000      0.059     -71.685    3668.493
 interest_rate       345.5401    111.367      3.103      0.005     113.940     577.140
 unemployment_rate  -250.1466    117.950     -2.121      0.046    -495.437      -4.856
 ==============================================================================
 Omnibus:                        2.691   Durbin-Watson:                   0.530
 Prob(Omnibus):                  0.260   Jarque-Bera (JB):                1.551
 Skew:                          -0.612   Prob(JB):                        0.461
 Kurtosis:                       3.226   Cond. No.                         394.
 ==============================================================================

 Notes:
 [1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
 """)

In [8]:
dir(model)

['HC0_se',
 'HC1_se',
 'HC2_se',
 'HC3_se',
 '_HCCM',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abat_diagonal',
 '_cache',
 '_data_attr',
 '_data_in_cache',
 '_get_robustcov_results',
 '_get_wald_nonlinear',
 '_is_nested',
 '_transform_predict_exog',
 '_use_t',
 '_wexog_singular_values',
 'aic',
 'bic',
 'bse',
 'centered_tss',
 'compare_f_test',
 'compare_lm_test',
 'compare_lr_test',
 'condition_number',
 'conf_int',
 'conf_int_el',
 'cov_HC0',
 'cov_HC1',
 'cov_HC2',
 'cov_HC3',
 'cov_kwds',
 'cov_params',
 'cov_type',
 'df_model',
 'df_resid',
 'diagn',
 'eigenvals',
 'el_test',
 'ess',
 'f_pvalue',
 'f_test',
 'fittedvalues',
 'fvalue',
 'get_influence',
 'get_prediction',
 'get_robustcov_results',
 'info_criteria',
 'initialize',
 'k_constant',
 'llf',
 'load',
 'model',
 'mse_model',
 'mse_resid',
 'mse_total',
 'nobs',
 'normalized_cov_params',
 'outlier_test',
 'params',
 'predict',
 'pvalues',
 'remove_data',
 'resid',
 'resid_pearson',
 'rsquared',
 'rsquared_adj',
 'save',
 'scale',
 'ssr',
 'summary',
 'summary2',
 't_test',
 't_test_pairwise',
 'tvalues',
 'uncentered_tss',
 'use_t',
 'wald_test',
 'wald_test_terms',
 'wresid']

In [12]:
model.bse, model.pvalues, model.scale, model.resid

(const                899.248075
 interest_rate        111.366922
 unemployment_rate    117.949869
 dtype: float64,
 const                0.058612
 interest_rate        0.005389
 unemployment_rate    0.046013
 dtype: float64,
 4978.984408140719,
 0      41.137611
 1      57.522633
 2      20.522633
 3     -43.477367
 4     -55.462710
 5      -7.433395
 6     -52.448053
 7      -5.063031
 8     -41.063031
 9      -8.048374
 10     66.351305
 11     61.380619
 12     58.395277
 13     37.765641
 14     -9.249016
 15     80.794955
 16    118.809613
 17     71.794955
 18      6.794955
 19    -11.205045
 20    -51.234359
 21    -30.190387
 22   -148.190387
 23   -158.205045
 dtype: float64)